export const PRESET_AUTOMOTIVE_ICONS = [
  "ABS Material Rounded.png",
  "Accessories .png",
  "Accu .png",
  "Air Conditioner iOS 17 Glyph.png",
  "Angle Grinder Material Rounded.png",
  "Angle Grinder iOS 17 Filled.png",
  "Approval iOS 17 Glyph.png",
  "Automatic Car Wash iOS 17 Filled.png",
  "Automation iOS 17 Glyph.png",
  "Automotive iOS 17 Glyph.png",
  "Car Badge Material Rounded.png",
  "Car Battery Material Filled.png",
  "Car Cleaning iOS 17 Glyph.png",
  "Car Door Material Rounded.png",
  "Car Fire iOS 17 Outlined.png",
  "Car Insurance iOS 17 Glyph.png",
  "Car Production iOS 17 Filled.png",
  "Car Rental iOS 17 Filled.png",
  "Car Seat iOS 17 Filled.png",
  "Car Service iOS 17 Glyph.png",
  "Car Theft iOS 17 Filled.png",
  "Car Wipers iOS 17 Filled.png",
  "Engine .png",
  "Engine Oil iOS 17 Glyph.png",
  "Exhaust .png",
  "Flat Tire Material Rounded.png",
  "Garage iOS 17 Glyph.png",
  "Gear Puffy Filled.png",
  "Grinding Machine iOS 17 Filled.png",
  "Hybrid iOS 17 Filled.png",
  "Motor Vehicle iOS 17 Glyph.png",
  "Pliers iOS 17 Filled.png",
  "Pressure iOS 17 Filled.png",
  "Race Car iOS 17 Glyph.png",
  "Radiator .png",
  "Service iOS 17 Glyph.png",
  "Speed iOS 17 Glyph.png",
  "Sustainable Energy iOS 17 Filled.png",
  "Tire Track iOS 17 Filled.png",
  "Tow Truck iOS 17 Filled.png",
  "Traction Control iOS 17 Glyph.png",
  "Turbo .png",
  "Washer Fluid iOS 17 Glyph.png",
  "Wheel .png"
]
