'use server'

import { GoogleGenerativeAI } from "@google/generative-ai"
import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { checkRateLimit, incrementRateLimit } from "@/lib/rate-limit"

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!)

export async function generateContent(formData: FormData) {
    const session = await auth()

    // Ensure User ID exists (required for rate limiting)
    if (!session?.user?.id || session?.user?.role !== "ADMIN") {
        return { success: false, message: "Unauthorized", content: "" }
    }

    // 🛡️ User ID is guaranteed string here due to the check above
    const userId = session.user.id

    // 🚦 Rate Limit: 10 requests per hour
    const canProceed = await checkRateLimit(userId, "GENERATE_ARTICLE", 10, 3600)
    if (!canProceed) {
        return {
            success: false,
            message: "Rate limit exceeded. You can generate up to 10 articles per hour.",
            content: ""
        }
    }

    const topic = formData.get("topic") as string
    const keywords = formData.get("keywords") as string
    const tone = formData.get("tone") as string

    if (!process.env.GEMINI_API_KEY) {
        // Fallback for demo/dev if no key provided
        console.warn("GEMINI_API_KEY not set. Using mock response.")
        await new Promise(r => setTimeout(r, 2000))
        return {
            success: true,
            content: `# ${topic}\n\n*Generated by Mock AI (Set GEMINI_API_KEY to use real AI)*\n\nThis is a placeholder article about **${topic}**. \n\nKeywords: ${keywords}\nTone: ${tone}\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit.`
        }
    }

    try {
        const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

        const prompt = `
      Write a professional SEO-optimized article about "${topic}".
      Target Keywords: ${keywords}
      Tone: ${tone}
      Format: Markdown.
      Structure:
      - Engaging Title (H1)
      - Introduction
      - Key Benefits/Features (H2)
      - Conclusion
      - FAQ (Optional)
    `

        const result = await model.generateContent(prompt)
        const response = await result.response
        const text = response.text()

        // 📝 Log Usage asynchronously (don't block response)
        // Rough estimate: 4 chars ~= 1 token
        const estimatedTokens = Math.ceil(text.length / 4)

        await prisma.aIUsageLog.create({
            data: {
                userId: userId,
                action: "GENERATE_ARTICLE",
                model: "gemini-2.5-flash",
                prompt: `Topic: ${topic} | Tone: ${tone}`,
                tokenCount: estimatedTokens,
                // cost: 0.000... (Calculate if needed)
            }
        })

        await incrementRateLimit(userId, "GENERATE_ARTICLE", 3600)

        return {
            success: true,
            content: text,
        }
    } catch (error) {
        console.error("AI Generation Error:", error)
        return {
            success: false,
            message: "Failed to generate content. Please check API Key or try again.",
            content: ""
        }
    }
}
